name: Days30
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  font_awesome_flutter: ^8.8.1
  flutter_emoji: ^2.2.1+1
  gradient_text: ^1.0.2
  charts_flutter: ^0.9.0
  flutter_svg: any
  flutter_statusbarcolor: ^0.2.3
  google_sign_in: ^4.5.1


  cupertino_icons: ^0.1.3
  # google_maps_flutter: ^0.5.28+1




dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: fonts/SourceSansPro-Regular.ttf
          weight: 200
        - asset: fonts/SourceSansPro-Bold.ttf
          weight: 600
        - asset: fonts/SourceSansPro-Black.ttf
          weight: 800

    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf
          weight: 200
        - asset: fonts/OpenSans-SemiBold.ttf
          weight: 600
        - asset: fonts/OpenSans-Bold.ttf
          weight: 800
    
    - family: BebasNeue
      fonts:
        - asset: fonts/BebasNeue-Regular.ttf

    - family: MoneyHeist
      fonts:
        - asset: fonts/MoneyHeistFont.ttf

    - family: AppleSF
      fonts:
        - asset: fonts/SF-Compact-Rounded-Regular.ttf
          weight: 100
        - asset: fonts/SF-Compact-Rounded-Medium.ttf
          weight: 200
        - asset: fonts/SF-Compact-Rounded-Semibold.ttf
          weight: 300
        - asset: fonts/SF-Compact-Rounded-Bold.ttf
          weight: 500

    - family: AppleSFMono
      fonts:
        - asset: fonts/SFMono-Regular.ttf
          weight: 100
        - asset: fonts/SFMono-Medium.ttf
          weight: 200
        - asset: fonts/SFMono-Bold.ttf
          weight: 500
        
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
